groups: []
resources:
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: prometheus-boshrelease.github-release
  type: github-release
  source:
    access_token: ((github-read-public-repos-token))
    owner: bosh-prometheus
    repository: prometheus-boshrelease
- name: deploy-prometheus.git
  type: git
  source:
    branch: child-envs
    uri: https://github.com/govau/deploy-prometheus.git
- name: ops.git
  type: git
  source:
    branch: master
    paths:
    - monitoring/probe_endpoints.yml
    private_key: ((ops-git-deploy-key))
    uri: git@github.com:AusDTO/ops.git
- name: slack
  type: slack-notification
  source:
    url: ((concourse-slack-webhook-url))
# - name: deployment-d-cld
#   type: bosh2-deployment
#   source:
#     ca_cert: ((d_bosh_ca_cert))
#     client: ((d_bosh_client))
#     client_secret: ((d_bosh_client_secret))
#     deployment: prometheus
#     jumpbox_ssh_key: ((d_jumpbox_ssh_key))
#     jumpbox_url: ((d_jumpbox_url))
#     target: ((d_bosh_target))
# - name: deployment-g-cld
#   type: bosh2-deployment
#   source:
#     ca_cert: ((g_bosh_ca_cert))
#     client: ((g_bosh_client))
#     client_secret: ((g_bosh_client_secret))
#     deployment: prometheus
#     jumpbox_ssh_key: ((g_jumpbox_ssh_key))
#     jumpbox_url: ((g_jumpbox_url))
#     target: ((g_bosh_target))
- name: deployment-root-dev
  type: bosh2-deployment
  source:
    ca_cert: ((root_bosh_ca_cert))
    client: ((root_bosh_client))
    client_secret: ((root_bosh_client_secret))
    deployment: prometheus-dev
    jumpbox_ssh_key: ((root_jumpbox_key))
    jumpbox_url: ((root_jumpbox_url)):((root_jumpbox_port))
    target: ((root_bosh_target))

- name: deployment-root
  type: bosh2-deployment
  source:
    ca_cert: ((root_bosh_ca_cert))
    client: ((root_bosh_client))
    client_secret: ((root_bosh_client_secret))
    deployment: prometheus
    jumpbox_ssh_key: ((root_jumpbox_key))
    jumpbox_url: ((root_jumpbox_url)):((root_jumpbox_port))
    target: ((root_bosh_target))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: bosh2-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: v2.8.1
jobs:
- name: fetch
  plan:
  - aggregate:
    - get: prometheus-boshrelease.github-release
      trigger: true
      params:
        include_source_tarball: true
    - get: ops.git
      trigger: true
    - get: deploy-prometheus.git
      trigger: true
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL - FAILED to fetch prometheus boshrelease
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $ATC_EXTERNAL_URL - Successfully fetched new prometheus boshrelease - $TEXT_FILE_CONTENT
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: prometheus-boshrelease.github-release/tag
- name: test-it
  plan:
  - aggregate:
    - get: stemcell
    - get: slack
      passed:
      - fetch
      trigger: true
    - get: ops.git
      passed:
      - fetch
    - get: prometheus-boshrelease.github-release
      passed:
      - fetch
      params:
        include_source_tarball: true
    - get: deploy-prometheus.git
      passed:
      - fetch
  - task: extract-release-src
    file: deploy-prometheus.git/ci/tasks/extract-release-src.yml
  - put: deployment-root-dev
    params:
      manifest: prometheus-boshrelease.src/manifests/prometheus.yml
      ops_files:
      - prometheus-boshrelease.src/manifests/operators/monitor-bosh.yml
      - deploy-prometheus.git/operators/deployment-name.yml
      - deploy-prometheus.git/operators/dta-platform.yml
      - deploy-prometheus.git/operators/monitor-http-probe.yml
      - deploy-prometheus.git/operators/bosh-exporter-fix.yml
      - deploy-prometheus.git/operators/increase-prometheus-global-scrape-timeout.yml
      releases:
      - prometheus-boshrelease.github-release/*.tgz
      stemcells:
      - stemcell/*.tgz
      vars:
        bosh_ca_cert: ((root_bosh_ca_cert))
        bosh_password: ((root_bosh_client_secret))
        bosh_url: ((root_bosh_target))
        bosh_username: ((root_bosh_client))
        deployment-name: prometheus-dev
        metrics_environment: root-cld-dev

      vars_files:
      - ops.git/monitoring/probe_endpoints.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL $BUILD_JOB_NAME- FAILED testing of prometheus boshrelease
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $ATC_EXTERNAL_URL $BUILD_JOB_NAME - Successfully tested prometheus boshrelease
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: test-it-cleanup
  plan:
  - aggregate:
    - get: slack
      passed:
      - test-it
      trigger: true
    - get: deployment-root-dev
      passed:
      - test-it
    - get: deploy-prometheus.git
      passed:
      - test-it
  - put: deployment-root-dev
    params:
      delete:
        enabled: true
        force: true
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL - FAILED cleaning up root-cld BOSH director
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: ship-it-root
  plan:
  - aggregate:
    - get: stemcell
      passed:
      - test-it
    - get: prometheus-boshrelease.github-release
      passed:
      - test-it
      params:
        include_source_tarball: true
    - get: ops.git
      passed:
      - test-it
    - get: deploy-prometheus.git
      passed:
      - test-it
  - task: generate-dns-values
    file: deploy-prometheus.git/ci/tasks/generate-dns-values.yml
    params:
      JUMPBOX: ((root_jumpbox_url))
      JUMPBOX_SSH_KEY: ((root_jumpbox_key))
  - task: extract-release-src
    file: deploy-prometheus.git/ci/tasks/extract-release-src.yml
  - put: deployment-root
    params:
      manifest: prometheus-boshrelease.src/manifests/prometheus.yml
      ops_files:
      - prometheus-boshrelease.src/manifests/operators/monitor-bosh.yml
      - prometheus-boshrelease.src/manifests/operators/alertmanager-web-external-url.yml
      - prometheus-boshrelease.src/manifests/operators/prometheus-web-external-url.yml
      - prometheus-boshrelease.src/manifests/operators/alertmanager-slack-receiver.yml
      - deploy-prometheus.git/operators/deployment-name.yml
      - deploy-prometheus.git/operators/dta-platform.yml
      - deploy-prometheus.git/operators/dta-platform-nginx-hosts.yml
      - deploy-prometheus.git/operators/dta-platform-monitor-cf-environments.yml
      - deploy-prometheus.git/operators/monitor-http-probe.yml
      - deploy-prometheus.git/operators/bosh-exporter-fix.yml
      - deploy-prometheus.git/operators/increase-prometheus-global-scrape-timeout.yml
      releases:
      - prometheus-boshrelease.github-release/*.tgz
      stemcells:
      - stemcell/*.tgz
      vars:
        alertmanager_slack_api_url: ((alertmanager_slack_api_url))
        alertmanager_slack_channel: ((alertmanager_slack_channel))
        alertmanager_web_external_url: ((alertmanager_web_external_url))
        b_cld_api_url: ((b_cld_api_url))
        b_cld_doppler_url: ((b_cld_doppler_url))
        b_cld_metrics_environment: ((b_cld_metrics_environment))
        b_cld_uaa_url: ((b_cld_uaa_url))
        bosh_ca_cert: ((bosh_ca_cert))
        bosh_password: ((bosh_client_secret))
        bosh_url: ((bosh_target))
        bosh_username: ((bosh_client))
        d_cld_api_url: ((d_cld_api_url))
        d_cld_doppler_url: ((d_cld_doppler_url))
        d_cld_metrics_environment: ((d_cld_metrics_environment))
        d_cld_uaa_url: ((d_cld_uaa_url))
        deployment-name: prometheus
        metrics_environment: root-cld
        prometheus_web_external_url: ((prometheus_web_external_url))
        skip_ssl_verify: false
        y_cld_api_url: ((y_cld_api_url))
        y_cld_doppler_url: ((y_cld_doppler_url))
        y_cld_metrics_environment: ((y_cld_metrics_environment))
        y_cld_uaa_url: ((y_cld_uaa_url))
      vars_files:
      - dns-details/dns-vars.yml
      - ops.git/monitoring/probe_endpoints.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: $ATC_EXTERNAL_URL - FAILED deployment of prometheus
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: $ATC_EXTERNAL_URL - Successfully deployed prometheus
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
