---
# Update Network name, persistent volumes and instance types for basic prometheus deployment

# Deploy to the Support Network in AWS
- type: replace
  path: /instance_groups/name=alertmanager/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=prometheus2/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=database/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=grafana/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=nginx/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=sandpit_env/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=staging_env/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=prod_env/networks/name=default/name?
  value: Support

# Update storage volume sizes for persistent services

# prometheus-boshrelease sets volume size using persistent_disk, so we remove
# these defaults and then set using persistent_disk_type to match our cloud-config.

- type: remove
  path: /instance_groups/name=alertmanager/persistent_disk?

- type: remove
  path: /instance_groups/name=prometheus2/persistent_disk?

- type: remove
  path: /instance_groups/name=database/persistent_disk?

- type: remove
  path: /instance_groups/name=grafana/persistent_disk?

- type: remove
  path: /instance_groups/name=sandpit_env/persistent_disk?

- type: remove
  path: /instance_groups/name=staging_env/persistent_disk?

- type: remove
  path: /instance_groups/name=prod_env/persistent_disk?

- type: replace
  path: /instance_groups/name=alertmanager/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=prometheus2/persistent_disk_type?
  value: 30GB

- type: replace
  path: /instance_groups/name=database/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=grafana/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=sandpit_env/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=staging_env/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=prod_env/persistent_disk_type?
  value: 10GB

# add monitoring vm_extension to instances (for security groups)
- type: replace
  path: /instance_groups/name=alertmanager/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=prometheus2/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=database/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=grafana/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=nginx/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=sandpit_env/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=staging_env/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=prod_env/vm_extensions?/-
  value: monitoring

# deploy small instances
- type: replace
  path: /instance_groups/name=alertmanager/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=prometheus2/vm_type?
  value: c4.large

- type: replace
  path: /instance_groups/name=database/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=grafana/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=nginx/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=sandpit_env/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=staging_env/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=prod_env/vm_type?
  value: small
