
# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=cloudfoundry_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/cloudfoundry_alerts/*.alerts

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=cloudfoundry_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Cloudfoundry?/files/-
  value: /var/vcap/jobs/cloudfoundry_dashboards/cf*.json

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Prometheus?/files/-
  value: /var/vcap/jobs/cloudfoundry_dashboards/prometheus*.json

# sort out linking now that there are >1 prometheus2 instances
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/provides?
  value:
    prometheus: {as: prometheus_monitoring_env}

- type: replace
  path: /instance_groups/name=prometheus2/properties?
  value:
    aliases:
      sandpit.prometheus:
        # - "*.sandpit-env.*.((deployment-name)).bosh"
        - "*.sandpit-env.*"
      staging.prometheus:
        - "*.staging-env.*"
      prod.prometheus:
        - "*.prod-env.*"


- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/consumes?
  value:
    prometheus: {from: prometheus_monitoring_env}

# Monitor Certwatch app - TODO tidy this up
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: certwatch
    metrics_path: /metrics
    static_configs:
    - targets: [certmetrics.apps.y.cld.gov.au]
