# Prometheus server and exporter jobs for SANDPIT environment (d.cld.gov.au)
- type: replace
  path: /instance_groups/-
  value:
    name: d-cld
    azs: [ z1, z2, z3 ]
    instances: 1
    vm_type: default
    persistent_disk: 10_240
    stemcell: default
    provides:
      prometheus: {as: prometheus_d_cld}
    networks:
      - name: default
    jobs:
      - name: cf_exporter
        release: prometheus
        properties:
          cf_exporter:
            cf:
              api_url: ((d_cld_api_url))
              client_id: cf_exporter
              client_secret: "((d_cld_uaa_clients_cf_exporter_secret))"
              deployment_name: cf
            metrics:
              environment: ((d_cld_metrics_environment))
      - name: firehose_exporter
        release: prometheus
        properties:
          firehose_exporter:
            doppler:
              url: ((d_cld_doppler_url))
              subscription_id: "((d_cld_metrics_environment))-((deployment-name))"
              max_retry_count: 300
            uaa:
              url: ((d_cld_uaa_url))
              client_id: firehose_exporter
              client_secret: "((d_cld_uaa_clients_firehose_exporter_secret))"
            metrics:
              environment: ((d_cld_metrics_environment))
      - name: bosh_exporter
        release: prometheus
        properties:
          bosh_exporter:
            bosh:
              url: "((d_cld_bosh_url))"
              uaa:
                client_id: ((d_cld_bosh_client))
                client_secret: ((d_cld_bosh_client_secret))
              ca_cert: "((d_cld_bosh_ca_cert))"
            metrics:
              environment: "((d_cld_metrics_environment))"
      - name: prometheus2
        release: prometheus
        provides:
          prometheus: {as: prometheus_d_cld}
        properties:
          prometheus:
            external_labels:
              cloud_env: d-cld
            rule_files:
              - /var/vcap/jobs/bosh_alerts/*.alerts.yml
              - /var/vcap/jobs/cloudfoundry_alerts/*.alerts.yml
              - /var/vcap/jobs/postgres_alerts/*.alerts.yml
              - /var/vcap/jobs/prometheus_alerts/*.alerts.yml
            scrape_configs:
              - job_name: prometheus
                static_configs:
                - targets:
                  - localhost:9090
              - job_name: bosh
                scrape_interval: 2m
                scrape_timeout: 1m
                static_configs:
                - targets:
                  - localhost:9190
      - name: bosh_alerts
        release: prometheus
      - name: cloudfoundry_alerts
        release: prometheus
      - name: postgres_alerts
        release: prometheus
      - name: prometheus_alerts
        release: prometheus

- type: replace
  path: /instance_groups/name=d-cld/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: haproxy
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: haproxy_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9101"
- type: replace
  path: /instance_groups/name=d-cld/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: node
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: node_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9100"
- type: replace
  path: /instance_groups/name=d-cld/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: postgres
    file_sd_configs:
      - files:
        - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"
    relabel_configs:
      - source_labels:
        - __meta_bosh_job_process_name
        regex: postgres_exporter
        action: keep
      - source_labels:
        - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9187"
